# fly.toml app configuration file generated for soi on 2023-08-10T09:16:38+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "soi"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
