
STATE_PREFIXES = ['THE ', 'STATE OF ', 'UNION TERRITORY OF ']
STATE_SUFFIXES = [' STATE']

DIVISION_PREFIXES = []
DIVISION_SUFFIXES = [' DIVISION']

DISTRICT_PREFIXES = ['THE ']
DISTRICT_SUFFIXES = [' DISTRICT']

SUBDIVISION_PREFIXES = []
SUBDIVISION_SUFFIXES = [ ' SUBDIVISION', ' DIVISION', ' REVENUE DIVISION' ]

SUBDISTRICT_PREFIXES = ['THE ']
SUBDISTRICT_SUFFIXES = [' SUBDISTRICT',
                        ' TEHSIL', ' TAHSIL',
                        ' TALUKA', ' TALUK', 
                        ' MANDAL', ' MANDALAM', ' MANDALA', 
                        ' COMMUNITY DEVELOPMENT BLOCK', ' BLOCK', ' C.D.BLOCK',
                        ' REVENUE CIRCLE', ' CIRCLE', ' CICLE', ' EAC', ' SDO', ' ADC', ' HQ',
                        ' SUBTEHSIL', ' ST',
                        ' SUBDIVISION',
                        ' P.S.', ' P.S', 'P.S.']

BLOCK_PREFIXES = ['THE ']
BLOCK_SUFFIXES = [' COMMUNITY DEVELOPMENT BLOCK', ' C.D. BLOCK', ' C.D BLOCK', ' BLOCK']

DISTRICT_PANCHAYAT_PREFIXES = [ 'DISTRICT PANCHAYAT OF' ]
DISTRICT_PANCHAYAT_SUFFIXES = [' ZILLA PARISHAD', ' ZILA PARISHAD', ' ZILLA PANCHAYAT',
                               ' DISTRICT PANCHAYAT', ' DISTRICT PLANNING AND DEVELOPMENT BOARD',
                               ' DISTRICT' ]

BLOCK_PANCHAYAT_SUFFIXES = [' PANCHAYAT SAMITI', ' PANCHAYAT UNION', ' MANDAL PANCHAYAT', ' ANCHALIK PANCHAYAT',
                            ' JANPAD PANCHAYAT', ' TALUKA PANCHAYAT', ' BLOCK DEVELOPMENT COUNCIL',
                            ' BLOCK PANCHAYAT', ' COMMUNE PANCHAYAT', ' KSHETRA PANCHAYAT',
                            ' BLOCK' ]
BLOCK_PANCHAYAT_PREFIXES = []

