name: LGD Monthly Compression

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:


jobs:
  Run-LGD-Compression:
    timeout-minutes: 600
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Setup swap
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10

      - uses: actions/checkout@v4.1.7

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Get current date
        run: echo "date=$(date +'%d%b%Y')" >> $GITHUB_OUTPUT
        id: date

      - name: Restore run data from cache
        uses: actions/cache/restore@v4
        with:
          path: |
            lgd/data/combined/
          key:  lgd-archive-data-v0-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            lgd-archive-data-v0-${{ steps.date.outputs.date }}-${{ github.run_number }}-
            lgd-archive-data-v0-${{ steps.date.outputs.date }}-

      - name: Compress data
        run: |
          cd lgd
          uv run utils/get_prev_month_year.py month_year.txt
          uv run utils/archive_prev_month.py $(cat month_year.txt)
          ./utils/generate_lists.sh lgd-archive
          ./utils/generate_lists.sh lgd-latest
        timeout-minutes: 600

      - name: Save run data to cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            lgd/data/combined/
          key:  lgd-archive-data-v0-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}

  BuildDocs:
    needs: Run-LGD-Compression
    uses: ./.github/workflows/docs.yml
    secrets: inherit

 
