name: LGD Daily Wikidata Sync Check

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:


jobs:
  Run-LGD-Wikidata-Sync-Check:
    env:
      GH_TOKEN: ${{ github.token }}
    timeout-minutes: 70
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          cache-dependency-glob: 'lgd/wikidata/requirements.check.txt'
          cache-suffix: 'lgd-wikidata-check'
        id: setup-uv
              
      - name: Get current date
        run: echo "date=$(date +'%d%b%Y')" >> $GITHUB_OUTPUT
        id: date

      - name: Restore daily run data from cache
        uses: actions/cache/restore@v4
        with:
          path: |
            lgd/wikidata/data/
          key:  data-raw-lgd-wikidata-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            data-raw-lgd-wikidata-${{ steps.date.outputs.date }}-${{ github.run_number }}-
            data-raw-lgd-wikidata-${{ steps.date.outputs.date }}-

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=<(echo ${{ secrets.GCP_AUTH }} | base64 -d)

      - name: Make Sync Reports
        run: |
          cd lgd/wikidata
          bash steps.sh
        timeout-minutes: 60

      - name: Upload Reports
        run: |
          cd lgd/wikidata
          gh release upload lgd-wikidata-sync reports/*.json --clobber
        timeout-minutes: 5

      - name: Cleanup data
        run: |
          cd lgd/wikidata
          rm -rf data/*
          rm -rf reports/

      - name: Save daily run data to cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            lgd/wikidata/data/
          key:  data-raw-lgd-wikidata-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}

  LGD-Wikidata-Sync-Check-Failure:
    needs: 
      - Run-LGD-Wikidata-Sync-Check
    if: |
      always() && needs.Run-LGD-Wikidata-Sync-Check.result == 'failure'
    uses: ./.github/workflows/common-pb-alert.yml
    secrets: inherit
    with:
      title: "LGD Wikidata Sync Check Run Failed"
      which-run: "self"

  BuildDocs:
    needs: 
      - Run-LGD-Wikidata-Sync-Check
    uses: ./.github/workflows/docs.yml
    secrets: inherit
