name: SOI Tile Run

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  workflow_dispatch:
  workflow_run:
    workflows:
      - "SOI Weekly Parse Run"
    type:
      - completed

jobs:
  Check-For-Work:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
    outputs: 
      work_item_count: ${{ steps.work.outputs.num_items }}  
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Check for work
        id: work
        run: |
          cd maps/SOI
          mkdir data
          util/get_work_for_tiler.sh data/to_retile.txt
          cat data/to_retile.txt
          num_items=$(wc -l data/to_retile.txt | tr -s " " | cut -d" " -f1)
          echo "num_items=$num_items"
          echo "num_items=$num_items" >> $GITHUB_OUTPUT


  Run-SOI-Tiling:
    needs: Check-For-Work
    if: ( github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' ) && needs.Check-For-Work.outputs.work_item_count != '0'
    timeout-minutes: 600
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ github.token }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Setup swap
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 12

      - uses: actions/checkout@v4.1.7

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Get current date
        run: echo "date=$(date +'%d%b%Y')" >> $GITHUB_OUTPUT
        id: date

      - name: Retile
        id: retile
        run: |
          mkdir -p temp
          TMPDIR=./temp 
          GDAL_VERSION=$(gdalinfo --version | cut -d"," -f1 | cut -d" " -f2)
          echo "GDAL_VERSION=$GDAL_VERSION"
          uvx --with numpy --with pillow --with gdal==$GDAL_VERSION --from topo_map_processor retile-e2e \
              --pmtiles-release soi-latest \
              --gtiffs-release soi-tiffs \
              --pmtiles-prefix soi \
              --listing-files-tiled "listing_files.csv"

      - name: Setup fly tools
        if: steps.retile.outcome == 'success'
        uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Restart Fly Server
        if: steps.retile.status == 'success'
        run: |
          flyctl scale count 0 --app indianopenmaps -y
          flyctl scale count 1 --app indianopenmaps -y

  SOI-Tile-Failure-Notify:
    needs: 
      - Run-SOI-Tiling
      - Check-For-Work
    if: always() && ( needs.Check-For-Work.result == 'failure' || needs.Run-SOI-Tiling.result == 'failure' )
    uses: ./.github/workflows/common-pb-alert.yml
    secrets: inherit
    with:
      title: "SOI Tile Run Failed"
      which-run: "self"

  BuildDocs:
    needs: 
      - Run-SOI-Tiling
      - Check-For-Work
    uses: ./.github/workflows/docs.yml
    secrets: inherit

