name: SOI Weekly Unavailable Pull Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:


jobs:
  Run-SOI-Extraction:
    timeout-minutes: 600
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: maps/SOI
          load: true
          build-args: |
            build_type=final
          tags: soi:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Restore tesseract models from cache
        uses: actions/cache@v3
        with:
          path: 'data/captcha/models/'
          key:  'SOI-tesseract-models-gcs-v2'
        id: models-cache

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=<(echo ${{ secrets.GCP_AUTH }} | base64 -d)

      - name: Download tesseract models from gcs
        if: ${{ steps.models-cache.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p data/captcha/models/
          gsutil -m cp -r gs://lgd_captcha_tesseract_models/* data/captcha/models/

      - name: Download users lists
        run: |
          gsutil -m cp gs://soi_private/users.json data/users.json
          gsutil -m cp gs://soi_private/users_extra.json data/users_extra.json

      - name: Prepare done list
        run: |
          gsutil ls gs://soi_data/raw/* | sed 's/^gs:\/\/soi_data\/raw\///g' > data/files_done.txt

      - name: Restore prev workspace
        uses: ramSeraph/cache-always@v0.0.1
        with:
          path: |
            data/raw/
            data/index.geojson
            data/cookies/
            data/tried_users.txt
          key:  SOI-data-ua-raw-v2-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            SOI-data-ua-raw-v2-${{ github.run_number }}-
            SOI-data-ua-raw-v2-

      # scrape things
      - name: Download SOI data
        run: |
          docker run -d --name runner -v $(pwd):/code -w /code soi:latest maps/SOI/scrape.py -u -r 15
          docker logs -f runner
          exit_code=$(docker inspect runner --format='{{.State.ExitCode}}')
          exit $((exit_code))
        timeout-minutes: 180

      - name: Cleanup Processes
        if: ${{ always() }}
        run: |
          docker stop runner || true
          docker kill runner || true
          docker rm runner || true

      - name: Upload raw files to gcs
        run: |
          [[ "$(gsutil ls gs://soi_data/index.geojson 2>/dev/null)" == "" ]] && gsutil -m cp data/index.geojson gs://soi_data/index.geojson
          [[ "$(gsutil ls gs://soi_data/raw/SOI_FONTS.zip 2>/dev/null)" == "" ]] && gsutil -m cp data/raw/SOI_FONTS.zip gs://soi_data/raw/SOI_FONTS.zip
          find data/raw/* && gsutil -m cp -r data/raw/*.pdf gs://soi_data/raw/ || true
          find data/raw/* && find data/raw/*.pdf > data/to_parse.txt && gsutil -m cp data/to_parse.txt gs://soi_data/to_parse.txt || true
          find data/raw/* && sh -c "ls data/raw/*.pdf | sed 's,data,gs://soi_data,g' | sed 's/.pdf/.pdf.unavailable/g' | xargs gsutil rm " || true
          rm -rf data/raw/*.pdf || true
          rm -rf data/raw/*.pdf.unavailable || true
          rm -rf data/cookies
          rm -rf data/tried_users.txt

      - name: Update lists
        run: |
          maps/SOI/generate_lists.sh
