name: SOI Deploy redirect

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  scrape:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: superfly/flyctl-actions/setup-flyctl@1.5
      - run: |
         cd infra/fly_soi_redir
         flyctl deploy --remote-only
