name: SOI Tile Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:


jobs:
  Check-For-Work:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    outputs: 
      work_item_count: ${{ steps.work.outputs.num_items }}  
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Check for work
        id: work
        run: |
          cd maps/SOI
          mkdir data
          util/get_work_for_tiler.sh data/to_retile.txt
          cat data/to_retile.txt
          num_items=$(wc -l data/to_retile.txt | tr -s " " | cut -d" " -f1)
          echo "num_items=$num_items"
          echo "num_items=$num_items" >> $GITHUB_OUTPUT


  Run-SOI-Tiling:
    needs: Check-For-Work
    if: needs.Check-For-Work.outputs.work_item_count != '0'
    timeout-minutes: 600
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - name: Setup swap
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 12

      - uses: actions/checkout@v4.1.7

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            maps/SOI/partition.py.lock
            maps/SOI/retile.py.lock
          version: ">=0.5.29"

      - name: Restore ancillary files from cache
        uses: ramSeraph/cache-always@v0.0.1
        with:
          path: |
            maps/SOI/data/index.geojson
          key: 'SOI-tile-basefiles-v1'
        id: base-files-cache

      - name: Install packages
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Get current date
        run: echo "date=$(date +'%d%b%Y')" >> $GITHUB_OUTPUT
        id: date

      - name: Retile
        id: retile
        run: |
          cd maps/SOI
          mkdir -p data
          util/get_work_for_tiler.sh data/to_retile.txt

          echo "=== downloading pmtiles files from soi-latest ==="
          mkdir -p export/pmtiles
          mkdir -p staging

          gh release download soi-latest -p '*' -D export/pmtiles

          mkdir -p staging/tiles/
          mkdir -p staging/gtiffs/

          echo "=== getting index file ==="
          [[ -f data/index.geojson ]] || wget -P data/ https://github.com/ramSeraph/opendata/releases/download/soi-ancillary/index.geojson

          echo "=== getting available tiff list ==="
          gh release download soi-tiffs -p list.txt
          cat list.txt | cut -d" " -f2 > gtiff_list.txt
          rm list.txt

          echo "=== getting list of tiffs to pull ==="
          GDAL_VERSION=$(gdalinfo --version | cut -d"," -f1 | cut -d" " -f2)
          echo "GDAL_VERSION=$GDAL_VERSION"
          uv run --with GDAL==${GDAL_VERSION} retile.py data/to_retile.txt gtiff_list.txt sheet_list.txt
          
          echo "=== downlaoding the tiffs ==="
          cmd=""
          while read p; do
            cmd="$cmd -p ${p}.tif"
          done < sheet_list.txt

          rm sheet_list.txt

          echo "=== running retiler ==="
          echo $cmd
          gh release download soi-tiffs $cmd -D staging/gtiffs/

          ls staging/gtiffs 

          uv run --with numpy --with pillow --with GDAL==${GDAL_VERSION} retile.py data/to_retile.txt gtiff_list.txt
          
          rm gtiff_list.txt
          rm -rf staging/gtiffs/

          echo "=== running partitioner ==="
          mkdir -p staging/pmtiles/
          mkdir temp

          TMPDIR=./temp uv run partition.py

          rm -rf export/
          rm -rf staging/tiles/*

          find staging/pmtiles -type f > release_files.txt || touch release_files.txt
          staging_files=$(cat release_files.txt)
          num_release_files=$(wc -l release_files.txt | tr -s " " | cut -d" " -f1)
          echo "num_release_files=$num_release_files"
          echo "num_release_files=$num_release_files" >> $GITHUB_OUTPUT
          echo "staging_files: $staging_files"
          echo "release_files<<EOF" >> $GITHUB_OUTPUT
          echo "$staging_files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          rm release_files.txt

      - name: Push pmtiles
        id: push-pmtiles
        if: steps.retile.outputs.num_release_files != '0'
        uses: ./.github/actions/releaser
        with:
          name: "SOI Open Series Maps"
          tag_name: soi-latest
          assets: ${{ steps.partition-pmtiles.outputs.release_files }}
          body: "SOI Open Series Maps as partitioned PMTiles."
          gh_token: ${{ secrets.github_token }}

      - name: Cleanup
        run: |
          gh release download soi-tiffs -p list.txt
          mv list.txt tiled_list.txt
          gh release upload soi-tiffs tiled_list.txt --clobber
          rm tiled_list.txt
          rm -rf staging/* || true

      - name: Setup fly tools
        if: steps.push-pmtiles.outcome == 'success'
        uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Restart Fly Server
        if: steps.push-pmtiles.status == 'success'
        run: |
          flyctl scale count 0 --app indianopenmaps -y
          flyctl scale count 1 --app indianopenmaps -y

  SOI-Tile-Failure-Notify:
    needs: 
      - Run-SOI-Tiling
      - Check-For-Work
    if: always() && ( needs.Check-For-Work.result == 'failure' || needs.Run-SOI-Tiling.result == 'failure' )
    uses: ./.github/workflows/common-pb-alert.yml
    secrets: inherit
    with:
      title: "SOI Tile Run Failed"
      which-run: "self"
