name: SOI Weekly Unavailable Pull Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


jobs:
  Run-SOI-Extraction:
    timeout-minutes: 600
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: docker/setup-buildx-action@v3.4.0
      - name: Build Image
        uses: docker/build-push-action@v6.3.0
        with:
          context: maps/SOI
          load: true
          build-args: |
            build_type=final
          tags: soi:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Restore tesseract models from cache
        uses: actions/cache@v4.0.2
        with:
          path: 'data/captcha/models/'
          key:  'SOI-tesseract-models-gcs-v2'
        id: models-cache

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=<(echo ${{ secrets.GCP_AUTH }} | base64 -d)

      - name: Download tesseract models from gcs
        if: ${{ steps.models-cache.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p data/captcha/models/
          gsutil -m cp -r gs://lgd_captcha_tesseract_models/* data/captcha/models/

      - name: Download users lists
        run: |
          gsutil -m cp gs://soi_private/users.json data/users.json
          gsutil -m cp gs://soi_private/users_extra.json data/users_extra.json

      - name: Prepare done list
        run: |
          gsutil ls gs://soi_data/raw/* | sed 's/^gs:\/\/soi_data\/raw\///g' > data/files_done.txt

      - name: Restore prev workspace
        uses: ramSeraph/cache-always@v0.0.1
        with:
          path: |
            data/raw/
            data/index.geojson
            data/cookies/
            data/tried_users.txt
          key:  SOI-data-ua-raw-v2-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            SOI-data-ua-raw-v2-${{ github.run_number }}-
            SOI-data-ua-raw-v2-

      - name: Bring up the proxy
        run: |
          ./infra/create.sh

      # scrape things
      - name: Download SOI data
        run: |
          docker run -d --name runner -v $(pwd):/code -w /code -e PROXY_URL="http://$(cat ip_address.txt):80" -e PB_TOKEN="${{ secrets.PB_TOKEN }}" soi:latest maps/SOI/scrape.py -u -p -r 25
          docker logs -f runner
          exit_code=$(docker inspect runner --format='{{.State.ExitCode}}')
          exit $((exit_code))
        timeout-minutes: 180

      - name: Cleanup Processes
        if: ${{ always() }}
        run: |
          docker stop runner || true
          docker kill runner || true
          docker rm runner || true

      - name: Bring down the proxy
        if: ${{ always() }}
        run: |
          if [[ -e info.sh ]]; then
            ./infra/destroy.sh 
          fi

      - name: Upload raw files to gcs
        run: |
          [[ "$(gsutil ls gs://soi_data/index.geojson 2>/dev/null)" == "" ]] && gsutil -m cp data/index.geojson gs://soi_data/index.geojson
          [[ "$(gsutil ls gs://soi_data/raw/SOI_FONTS.zip 2>/dev/null)" == "" ]] && gsutil -m cp data/raw/SOI_FONTS.zip gs://soi_data/raw/SOI_FONTS.zip
          find data/raw/* && gsutil -m cp -r data/raw/*.pdf gs://soi_data/raw/ || true
          find data/raw/* && find data/raw/*.pdf > data/to_parse.txt && gsutil -m cp data/to_parse.txt gs://soi_data/to_parse.txt || true
          find data/raw/* && sh -c "ls data/raw/*.pdf | sed 's,data,gs://soi_data,g' | sed 's/.pdf/.pdf.unavailable/g' | xargs gsutil rm " || true
          docker run --name cleaner -v $(pwd):/code -w /code --entrypoint "/bin/sh" soi:latest -c "rm -rf data/"

      - name: Update lists
        run: |
          maps/SOI/generate_lists.sh
