name: SOI Tile Run

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:


env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  Run-SOI-Parsing:
    timeout-minutes: 600
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Setup swap
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: |
            maps/SOI/partition.py.lock
            maps/SOI/retile.py.lock
          version: ">=0.5.29"

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Get current date
        run: echo "date=$(date +'%d%b%Y')" >> $GITHUB_OUTPUT
        id: date

      - name: Restore run data from cache
        uses: ramSeraph/cache-always@v0.0.1
        with:
          path: |
            staging/
            export/
            !export/pmtiles/*
          key:  soi-gcs-v6-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            soi-gcs-v6-${{ steps.date.outputs.date }}-${{ github.run_number }}-
            soi-gcs-v6-${{ steps.date.outputs.date }}-

      - name: Retile
        id: retile
        run: |
          cd maps/SOI
          util/get_work_for_tiler.sh data/to_retile.txt
          num_sheets=$(wc -l data/to_retile.txt | tr -s" " | cut -d" " -f2)
          if [[ $num_sheets == 0 ]]; then
            echo "num_release_files=0" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [[ ! -e staging/download_done ]]; then
            echo "=== downloading pmtiles files from soi-latest ==="
            mkdir -p export/pmtiles
            gh release download soi-latest -D export/pmtiles
            mkdir -p staging
            touch staging/download_done
          fi

          if [[ ! -e staging/retiling_done ]]; then
            mkdir -p export/tiles/
            mkdir -p staging/tiles/
            mkdir -p staging/pmtiles/
            echo "=== running retiler ==="
            GDAL_VERSION=$(gdalinfo --version | cut -d"," -f1 | cut -d" " -f2)
            uv run --with GDAL==${GDAL_VERSION} retile.py data/to_retile.txt
            rm -rf export/gtiffs/
            rm -rf export/tiles/
            rm -rf staging/gtiffs/
            touch staging/retiling_done
          fi

          if [[ ! -e staging/partitioned ]]; then
            mkdir temp
            TMPDIR=./temp uv run partition.py
            rm -rf export/
            rm -rf staging/tiles/*
            touch staging/partitioned
          fi

          find staging/pmtiles -type f > release_files.txt || touch release_files.txt
          staging_files=$(cat release_files.txt)
          num_release_files=$(wc -l release_files.txt | tr -s " " | cut -d" " -f2)
          echo "num_release_files=$num_release_files" >> $GITHUB_OUTPUT
          echo "staging_files: $staging_files"
          echo "release_files<<EOF" >> $GITHUB_OUTPUT
          echo "$staging_files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          rm release_files.txt

      - name: Push pmtiles
        id: push-pmtiles
        if: steps.retile.outputs.num_release_files != '0'
        uses: ./.github/actions/releaser
        with:
          name: "SOI Open Series Maps"
          tag_name: soi-latest
          assets: ${{ steps.partition-pmtiles.outputs.release_files }}
          body: "SOI Open Series Maps as partitioned PMTiles."
          gh_token: ${{ secrets.github_token }}

      - name: Cleanup
        run: |
          gh release download soi-tiffs list.txt
          mv list.txt tiled_list.txt
          gh release upload soi-tiffs tiled_list.txt --clobber
          rm tiled_list.txt
          rm -rf staging/* || true

      - name: Setup fly tools
        if: steps.push-pmtiles.outcome == 'success'
        uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Restart Fly Server
        if: steps.push-pmtiles.status == 'success'
        run: |
          flyctl scale count 0 --app indianopenmaps -y
          flyctl scale count 1 --app indianopenmaps -y
