name: SOI Weekly Parse Run

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on: 
  workflow_run:
    workflows:
      - "SOI Weekly Unavailable Pull Run"
    type:
      - completed
  workflow_dispatch:


jobs:
  Check-For-Work:
    runs-on: ubuntu-22.04
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    env:
      GH_TOKEN: ${{ github.token }}
    outputs: 
      work_item_count: ${{ steps.work.outputs.num_items }}  
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: astral-sh/setup-uv@v5
      - name: Check for work
        id: work
        run: |
          cd maps/SOI
          mkdir data
          util/get_work_for_parser.sh data/to_parse.txt
          cat data/to_parse.txt
          num_items=$(wc -l data/to_parse.txt | tr -s " " | cut -d" " -f1)
          echo "num_items=$num_items"
          echo "num_items=$num_items" >> $GITHUB_OUTPUT

  Run-SOI-Parsing:
    needs: Check-For-Work
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' && needs.Check-For-Work.outputs.work_item_count != '0'
    timeout-minutes: 600
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Setup swap
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 12
      - uses: actions/checkout@v4.1.7

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: maps/SOI/parse.py.lock

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Restore parse tools from cache
        uses: actions/cache/restore@v4
        with:
          path: maps/SOI/bin/
          key:  soi-parse-tools-v5
        id: tools-cache

      - name: Install tools
        if: ${{ steps.tools-cache.outputs.cache-hit != 'true' }}
        run: |
          cd maps/SOI
          if [[ ! -f bin/mutool ]]; then
            sudo apt-get install -y llvm
            CXX=clang++ AR=llvm-ar util/build_mutool.sh
          fi

      - name: Save parse tools to cache
        if: ${{ steps.tools-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: maps/SOI/bin/
          key:  soi-parse-tools-v5

      - name: Restore ancillary files from cache
        uses: actions/cache/restore@v4
        with:
          path: |
            maps/SOI/data/index.geojson
            maps/SOI/data/raw/SOI_FONTS.zip
          key: 'SOI-parse-basefiles-v1'
        id: base-files-cache

      - name: Download Ancillary data
        if: ${{ steps.base-files-cache.outputs.cache-hit != 'true' }}
        run: |
          cd maps/SOI

          [[ -f data/raw/SOI_FONTS.zip ]] || wget -P data/raw/ https://github.com/ramSeraph/opendata/releases/download/soi-ancillary/SOI_FONTS.zip 
          [[ -f data/index.geojson ]] || wget -P data/ https://github.com/ramSeraph/opendata/releases/download/soi-ancillary/index.geojson


      - name: Save ancillary files to cache
        if: ${{ steps.base-files-cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: |
            maps/SOI/data/index.geojson
            maps/SOI/data/raw/SOI_FONTS.zip
          key: 'SOI-parse-basefiles-v1'


      - name: Get current date
        run: echo "date=$(date +'%d%b%Y')" >> $GITHUB_OUTPUT
        id: date

      - name: Restore parse run data from cache
        uses: actions/cache/restore@v4
        with:
          path: |
            maps/SOI/data/raw/*.pdf
            maps/SOI/export/gtiffs/
          key:  soi-gcs-parse-v4-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            soi-gcs-parse-v4-${{ steps.date.outputs.date }}-${{ github.run_number }}-
            soi-gcs-parse-v4-${{ steps.date.outputs.date }}-


      - name: Parse SOI sheets
        run: |
          cd maps/SOI

          [[ -f data/raw/SOI_FONTS.zip ]] || wget -P data/raw/ https://github.com/ramSeraph/opendata/releases/download/soi-ancillary/SOI_FONTS.zip 
          [[ -f data/index.geojson ]] || wget -P data/ https://github.com/ramSeraph/opendata/releases/download/soi-ancillary/index.geojson

          util/get_work_for_parser.sh data/to_parse.txt
          util/download_sheets.sh data/to_parse.txt

          uv run check_duplicates.py data/to_parse.txt

          mkdir -p export/gtiffs/

          echo "Running parse.py"
          GDAL_VERSION=$(gdalinfo --version | cut -d"," -f1 | cut -d" " -f2)
          FROM_LIST=data/to_parse.txt uv run --with GDAL==${GDAL_VERSION} parse.py
          
          echo "Parse run completed, generating lists and uploading to release"
          uvx --from topo_map_processor upload-to-release soi-tiffs export/gtiffs tif 

          echo "Generating lists"
          uvx --from topo_map_processor generate-lists soi-tiffs .tif

          echo "Generating bounds file and uploading"
          gh reelease download soi-tiffs -p 'listing_files.csv' 
          uv run filter_index_file.py data/index.geojson data/bounds.geojson listing_files.csv
          gh release upload soi-tiffs data/bounds.geojson --clobber
          rm listing_files.csv
          rm data/bounds.geojson

          rm -rf data/raw/* || true
          rm -rf export/gtiffs/* || true
        timeout-minutes: 600
 
      - name: Save parse run data to cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            maps/SOI/data/raw/*.pdf
            maps/SOI/export/gtiffs/
          key:  soi-gcs-parse-v4-${{ steps.date.outputs.date }}-${{ github.run_number }}-${{ github.run_attempt }}


  SOI-Parse-Failure-Notify:
    needs: 
      - Run-SOI-Parsing
      - Check-For-Work
    if: always() && ( needs.Check-For-Work.result == 'failure' || needs.Run-SOI-Parsing.result == 'failure' )
    uses: ./.github/workflows/common-pb-alert.yml
    secrets: inherit
    with:
      title: "SOI Parse Run Failed"
      which-run: "self"

  BuildDocs:
    needs: 
      - Run-SOI-Parsing
      - Check-For-Work
    uses: ./.github/workflows/docs.yml
    secrets: inherit

